version: '3.7'
services:
  reverse_proxy_service:
    image: nginx-learning:latest
    ports:
    - 9989:80
    depends_on:
    - audi
    - mercedes
    networks:
      dockernet1:
        aliases:
          - reverse

  audi:
    image: audi-app:latest
    ports:
    - 8098:8099
    networks:
       dockernet1:
         aliases:
           - audi-rule-engine.com
  mercedes:
    image: mercedes-app:latest
    ports:
      - 7098:8099
    networks:
      dockernet1:
        aliases:
          - mercedes-rule-engine.com

networks:
  dockernet1:
  #  external: true



